name: 'Seqra + ZAP PR Differential Scan'
description: 'Security-focused differential scanning for pull requests using Seqra SAST and ZAP DAST'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  project-root:
    description: 'Relative path to the project root'
    default: '.'
  openapi-spec:
    description: 'Path or URL to OpenAPI specification'
    required: true
  target-url:
    description: 'Target application URL for ZAP scanning'
    required: true
  zap-input-vector:
    description: 'ZAP input vector mask (default: 31 = all)'
    default: '31'
  zap-rpc:
    description: 'ZAP RPC parameter'
    default: '5'
  cwe-config:
    description: 'Path to CWE scanner configuration YAML'
    required: true

outputs:
  results-file:
    description: 'Path to the scan results JSON file'
    value: ${{ steps.scan.outputs.results_file }}
  filtered-sarif:
    description: 'Path to the Seqra SARIF filtered by confirmed ZAP findings'
    value: ${{ steps.scan.outputs.filtered_sarif }}

runs:
  using: 'composite'
  steps:
    - name: Determine branches
      id: branches
      shell: bash
      run: |
        if [ -n "${{ github.event.pull_request.base.ref }}" ]; then
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
        else
          BASE_BRANCH="main"
        fi

        if [ -n "${{ github.event.pull_request.head.ref }}" ]; then
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
        else
          HEAD_BRANCH="${{ github.ref_name }}"
        fi

        echo "base=$BASE_BRANCH" >> $GITHUB_OUTPUT
        echo "head=$HEAD_BRANCH" >> $GITHUB_OUTPUT
        echo "Base branch: $BASE_BRANCH"
        echo "Head branch: $HEAD_BRANCH"

    - name: Setup UV
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install Python dependencies
      shell: bash
      run: |
        uv sync --frozen

    - name: Scan PR branch with Seqra
      uses: seqra/seqra-action@v2
      with:
        project-root: ${{ inputs.project-root }}
        artifact-name: 'seqra-pr'

    - name: Checkout base branch
      uses: actions/checkout@v6
      with:
        ref: ${{ steps.branches.outputs.base }}
        path: base-branch

    - name: Scan base branch with Seqra
      uses: seqra/seqra-action@v2
      with:
        project-root: base-branch/${{ inputs.project-root }}
        artifact-name: 'seqra-base'

    - name: Download PR SARIF
      id: scan-pr
      uses: actions/download-artifact@v4
      with:
        name: 'seqra-pr'
        path: ${{ runner.temp }}/seqra-pr

    - name: Download base SARIF
      id: scan-base
      uses: actions/download-artifact@v4
      with:
        name: 'seqra-base'
        path: ${{ runner.temp }}/seqra-base

    - name: Run ZAP differential scan
      id: scan
      shell: bash
      env:
        NEW_SARIF: ${{ runner.temp }}/seqra-pr/seqra.sarif
        OLD_SARIF: ${{ runner.temp }}/seqra-base/seqra.sarif
        OPENAPI_SPEC: ${{ inputs.openapi-spec }}
        TARGET_URL: ${{ inputs.target-url }}
        INPUT_VECTOR: ${{ inputs.zap-input-vector }}
        RPC: ${{ inputs.zap-rpc }}
        CWE_CONFIG: ${{ inputs.cwe-config }}
        OUTPUT_FILE: ${{ runner.temp }}/scan-results.json
      run: |
        uv run python ${{ github.action_path }}/scan_ci.py
        echo "results_file=${{ runner.temp }}/scan-results.json" >> "$GITHUB_OUTPUT"

    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: zap-scan-results
        path: ${{ runner.temp }}/scan-results.json
        retention-days: 30

    - name: Upload confirmed SARIF artifact
      if: steps.scan.outputs.filtered_sarif != ''
      uses: actions/upload-artifact@v4
      with:
        name: seqra-confirmed-sarif
        path: ${{ steps.scan.outputs.filtered_sarif }}
        retention-days: 30

    - name: Upload confirmed findings to Code Scanning
      if: steps.scan.outputs.filtered_sarif != ''
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ steps.scan.outputs.filtered_sarif }}
        category: seqra-confirmed
